# Generated by Django 5.0.3 on 2024-04-02 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants_quantity', models.IntegerField(default=1)),
                ('pots_quantity', models.IntegerField(default=1)),
                ('pebbles_quantity', models.IntegerField(default=1)),
                ('fertilisers_quantity', models.IntegerField(default=1)),
                ('seeds_quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('fertilisers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.fertilisers_products')),
                ('pebbles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.pebbles_products')),
                ('plants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.plants_products')),
                ('pots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.pots_products')),
                ('seeds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.seeds_products')),
            ],
        ),
    ]
